services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_vehicle_renting
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: vehicle_renting
    volumes:
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
  
  gtmotive.microservice.host:
    image: ${DOCKER_REGISTRY-}gtmotivemicroservicehost
    build:
        context: .
        dockerfile: src/GtMotive.Microservice.Host/Dockerfile
    container_name: gtmotive_vehicles.micro.host
    ports:
      - "5069:8080"
    environment:
      - PostgreSQL__ConnectionString=Server=postgres;Port=5432;Database=vehicle_renting;User Id=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080 
volumes:
  postgres_data: